### ISSUE TITLE
What is this trash?

### ISSUE THREAD

**Issue by chukfinley** [ThatNotEasy/Music-Downloader#1]
This does not download music from spotify in any way it may scrape YouTube but nothing more. 
It you want a real tools search for doubledouble . top vor there New domain.

**Comment by Ap0dexMe0** [comment]
> This does not download music from spotify in any way it may scrape YouTube but nothing more. It you want a real tools search for doubledouble . top vor there New domain.

Oh, forgive me, I may have "blinded" myself to your greatness. Perhaps you could help me see more clearly what I've overlooked. It's okay, sometimes I really need "excellent guidance" like the one you provided. And wow, the URL you gave is SO REAL!!!
